server:
 port: 8891

spring:
 application:
  name: API-Gateway

eureka:
 client:
  eureka-server-port: 7777

zuul:
 routes:
  abc:
   path: /demo/**
   service-id: MY-SERVICE
  xyz:
   path: /test/**
   service-id: MY-CLIENT-SERVICE



#server.port=8891
#
#spring.application.name=API-Gateway
#
#eureka.client.eureka-server-port=7777
#
#zuul.routes.abc.path=/demo/**
#zuul.routes.abc.service-id=MY-SERVICE
#
#zuul.routes.xyz.path=/test/**
#zuul.routes.xyz.service-id=MY-CLIENT-SERVICE
